// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/7/2024, 4:01:44 PM
const configMerger = require("/Users/7ofunm1/Desktop/Vue/muse/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.1_magicast@0.3.5_rollup@4.21.2/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/7ofunm1/Desktop/Vue/muse/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/7ofunm1/Desktop/Vue/muse/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/7ofunm1/Desktop/Vue/muse/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/7ofunm1/Desktop/Vue/muse/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/7ofunm1/Desktop/Vue/muse/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/7ofunm1/Desktop/Vue/muse/plugins/**/*.{js,ts,mjs}","/Users/7ofunm1/Desktop/Vue/muse/composables/**/*.{js,ts,mjs}","/Users/7ofunm1/Desktop/Vue/muse/utils/**/*.{js,ts,mjs}","/Users/7ofunm1/Desktop/Vue/muse/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/7ofunm1/Desktop/Vue/muse/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/7ofunm1/Desktop/Vue/muse/app.config.{js,ts,mjs}"] }));

module.exports = config
